resilience4j:
  circuitbreaker:
    instances:
      CircuitBreakerService:
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 15s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: count_based
  retry:
    instances:
      RetryService:
        max-attempts: 3
        wait-duration: 1s
    metrics:
      legacy:
        enabled: true
      enabled: true
  bulkhead:
    metrics:
      enabled: true
    instances:
      BulkheadService:
        max-concurrent-calls: 3
        max-wait-duration: 1
  ratelimiter:
    metrics:
      enabled: true
    instances:
      RateLimiterService:
        register-health-indicator: true
        limit-for-period: 5
        limit-refresh-period: 60s
        timeout-duration: 0s
        allow-health-indicator-to-fail: true
        subscribe-for-events: true
        event-consumer-buffer-size: 50

